services:
    mysql:
        image: mariadb:11.4
        logging:
            driver: none
        command: ['--max-allowed-packet=512M']
        volumes:
            - mysql-data:/var/lib/mysql:delegated
        environment:
            - MYSQL_ROOT_PASSWORD= ${SERVICE_PASSWORD_MYSQLROOT:-root}
            - MYSQL_DATABASE=wordpress
            - MYSQL_USER=${SERVICE_USER_DB:-user}
            - MYSQL_PASSWORD=${SERVICE_PASSWORD_DB:-password}

    litespeed:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                OLS_VERSION: ${OLS_VERSION:-1.8.2}
                PHP_VERSION: ${PHP_VERSION:-lsphp82}
                WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST:-mysql}
                WORDPRESS_DB_USER: ${SERVICE_USER_DB:-user}
                WORDPRESS_DB_PASSWORD: ${SERVICE_PASSWORD_DB:-password}
                WORDPRESS_DB_NAME: wordpress
        environment:
            - SERVICE_FQDN_LITESPEED
            - WORDPRESS_DB_HOST= ${WORDPRESS_DB_HOST:-mysql}
            - WORDPRESS_DB_USER= ${SERVICE_USER_DB:-user}
            - WORDPRESS_DB_PASSWORD= ${SERVICE_PASSWORD_DB:-password}
            - WORDPRESS_DB_NAME= wordpress
            - TZ= ${TZ:-Europe/Paris}
        volumes:
            - /mnt/d/www:/var/www/vhosts/localhost/html
        ports:
            - 80
            - 443
            - 443/udp

    redis:
        image: 'redis:latest'
        restart: 'always'
        ports:
            - 6379
        healthcheck:
            test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
            interval: 10s
            timeout: 10s
            retries: 10
