services:
    mysql:
        image: mariadb:11.4
        logging:
            driver: none
        command: ['--max-allowed-packet=512M']
        volumes:
            - mysql-data:/var/lib/mysql:delegated
        environment:
            MYSQL_ROOT_PASSWORD: ${SERVICE_PASSWORD_MYSQLROOT:-root}
            MYSQL_DATABASE: wordpress
            MYSQL_USER: ${SERVICE_USER_MYSQL:-user}
            MYSQL_PASSWORD: ${SERVICE_PASSWORD_MYSQL:-password}

    litespeed:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                OLS_VERSION: ${OLS_VERSION:-1.8.2}
                PHP_VERSION: ${PHP_VERSION:-lsphp82}
                SERVICE_FQDN_LITESPEED: ${SERVICE_FQDN_LITESPEED:-localhost}
                SERVICE_USER_WORDPRESS: ${SERVICE_USER_WORDPRESS:-user}
                SERVICE_PASSWORD_WORDPRESS: ${SERVICE_PASSWORD_WORDPRESS:-password}
        volumes:
            - /mnt/d/www:/var/www/vhosts/localhost/html
        ports:
            - 80
            - 443
            - 443/udp
        environment:
            TZ: ${TZ:-Europe/Paris}

    redis:
        image: 'redis:latest'
        restart: 'always'
        ports:
            - 6379
        healthcheck:
            test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
            interval: 10s
            timeout: 10s
            retries: 10
