services:
    litespeed:
        build:
            context: .
            dockerfile: Dockerfile
        image: litespeedtech/openlitespeed
        environment:
            - SERVICE_FQDN_LITESPEED
            - WORDPRESS_DB_HOST=mariadb
            - 'DB_HOST=mariadb'
            - 'WORDPRESS_DB_USER=${SERVICE_USER_WORDPRESS:-user}'
            - 'WORDPRESS_DB_PASSWORD=${SERVICE_PASSWORD_WORDPRESS:-password}'
            - 'WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME:-wordpress}'
        volumes:
            - 'wordpress-files:/var/www/vhosts/localhost/html'
        depends_on:
            mariadb:
                condition: service_healthy
        ports:
            - 80
            - 443
        # healthcheck:
        #     test: ['CMD', 'curl', '-f', 'http://localhost']
        #     interval: 2s
        #     timeout: 10s
        #     retries: 10
        # restart: always

    redis:
        image: 'redis:latest'
        restart: 'always'
        ports:
            - 6379
        healthcheck:
            test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
            interval: 10s
            timeout: 10s
            retries: 10

    mariadb:
        image: 'mariadb:11'
        ports:
            - 3306
        volumes:
            - 'mariadb-data:/var/lib/mysql'
        environment:
            - 'MARIADB_ROOT_PASSWORD=${SERVICE_PASSWORD_MARIADB:-passworddb}'
            - 'MARIADB_DATABASE=${WORDPRESS_DB_NAME:-wordpress}'
            - 'MARIADB_USER=${SERVICE_USER_MARIADB:-userdb}'
            - 'MARIADB_PASSWORD=${SERVICE_PASSWORD_MARIADB:-passworddb}'
        healthcheck:
            test:
                - CMD
                - healthcheck.sh
                - '--connect'
                - '--innodb_initialized'
            interval: 5s
            timeout: 20s
            retries: 10
