services:
    mysql:
        image: mariadb:11.4
        logging:
            driver: none
        command: ['--max-allowed-packet=512M']
        volumes:
            - mysql-data:/var/lib/mysql:delegated
        environment:
            MYSQL_ROOT_PASSWORD: ${SERVICE_PASSWORD_MYSQLROOT:-root}
            MYSQL_DATABASE: wordpress
            MYSQL_USER: ${SERVICE_USER_MYSQL:-user}
            MYSQL_PASSWORD: ${SERVICE_PASSWORD_MYSQL:-password}

    litespeed:
        image: litespeedtech/openlitespeed:${OLS_VERSION:-1.8.2}-${PHP_VERSION:-lsphp82}
        volumes:
            - lsws-conf:/usr/local/lsws/conf
            - lsws-admin-conf:/usr/local/lsws/admin/conf
            - bin-container:/usr/local/bin
            - sites:/var/www/vhosts/
            - wordpress-files:/var/www/vhosts/localhost/html
            - acme:/root/.acme.sh/
            - logs:/usr/local/lsws/logs/
        ports:
            - 80
            - 443
            - 443/udp
        environment:
            TZ: ${TZ:-Europe/Paris}

    wordpress:
        image: wordpress:fpm
        volumes:
            - wordpress-files:/var/www/vhosts/localhost/html
        environment:
            WORDPRESS_DB_HOST: mysql
            WORDPRESS_DB_USER: ${SERVICE_USER_WORDPRESS:-user}
            WORDPRESS_DB_PASSWORD: ${SERVICE_PASSWORD_WORDPRESS:-password}
            WORDPRESS_DB_NAME: wordpress

    redis:
        image: 'redis:latest'
        restart: 'always'
        ports:
            - 6379
        healthcheck:
            test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
            interval: 10s
            timeout: 10s
            retries: 10
