services:
    wordpress:
        build:
            context: .
            dockerfile: Dockerfile
        #image: 'wordpress:fpm'
        volumes:
            - 'wordpress-files:/var/www/html'
        environment:
            - WORDPRESS_DB_HOST=mariadb
            - WORDPRESS_DB_USER=${SERVICE_USER_WORDPRESS:-user}
            - WORDPRESS_DB_PASSWORD=${SERVICE_PASSWORD_WORDPRESS:-password}
            - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME:-wordpress}
        depends_on:
            mariadb:
                condition: service_healthy
            # litespeed:
            #     condition: service_healthy

    litespeed:
        image: litespeedtech/openlitespeed
        ports:
            - 80
            - 443
        environment:
            - SERVICE_FQDN_LITESPEED
            - WORDPRESS_DB_HOST=mariadb
            - WORDPRESS_DB_USER=${SERVICE_USER_WORDPRESS:-user}
            - WORDPRESS_DB_PASSWORD=${SERVICE_PASSWORD_WORDPRESS:-password}
            - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME:-wordpress}
        volumes:
            - 'wordpress-files:/var/www/vhosts/localhost/html'
        depends_on:
            mariadb:
                condition: service_healthy
        # healthcheck:
        #     test: ['CMD', 'curl', '-f', 'http://localhost:80']
        #     interval: 2s
        #     timeout: 10s
        #     retries: 10
        restart: always

    redis:
        image: 'redis:latest'
        restart: 'always'
        healthcheck:
            test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
            interval: 10s
            timeout: 10s
            retries: 10

    mariadb:
        image: 'mariadb:11'
        volumes:
            - 'mariadb-data:/var/lib/mysql'
        environment:
            - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
            - MYSQL_DATABASE=wordpress
            - MYSQL_USER=$DB_USER
            - MYSQL_PASSWORD=$DB_PASSWORD
        healthcheck:
            test:
                - CMD
                - healthcheck.sh
                - '--connect'
                - '--innodb_initialized'
            interval: 5s
            timeout: 20s
            retries: 10
