version: '3.8'

services:
    wordpress:
        build:
            context: .
            dockerfile: Dockerfile
        image: 'wordpress:fpm'
        volumes:
            - 'wordpress-files:/var/www/html'
        environment:
            - WORDPRESS_DB_HOST=mariadb
            - WORDPRESS_DB_USER=${SERVICE_USER_WORDPRESS}
            - WORDPRESS_DB_PASSWORD=${SERVICE_PASSWORD_WORDPRESS}
            - WORDPRESS_DB_NAME=wordpress
        depends_on:
            mariadb:
                condition: service_healthy
            # litespeed:
            #     condition: service_healthy
        networks:
            - wordpress_network

    litespeed:
        image: litespeedtech/openlitespeed
        ports:
            - 80
            - 443
        environment:
            - SERVICE_FQDN_WORDPRESS
        volumes:
            - 'wordpress-files:/var/www/vhosts/localhost/html'
        depends_on:
            mariadb:
                condition: service_healthy
        # healthcheck:
        #     test: ['CMD', 'curl', '-f', 'http://localhost:80']
        #     interval: 2s
        #     timeout: 10s
        #     retries: 10
        restart: always
        networks:
            - wordpress_network

    redis:
        image: 'redis:latest'
        restart: 'always'
        networks:
            - wordpress_network
        healthcheck:
            test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
            interval: 10s
            timeout: 10s
            retries: 10

    mariadb:
        image: 'mariadb:11'
        volumes:
            - 'mariadb-data:/var/lib/mysql'
        environment:
            - MYSQL_ROOT_PASSWORD=${SERVICE_PASSWORD_ROOT}
            - MYSQL_DATABASE=wordpress
            - MYSQL_USER=${SERVICE_USER_WORDPRESS}
            - MYSQL_PASSWORD=${SERVICE_PASSWORD_WORDPRESS}
        healthcheck:
            test:
                - CMD
                - healthcheck.sh
                - '--connect'
                - '--innodb_initialized'
            interval: 5s
            timeout: 20s
            retries: 10
        networks:
            - wordpress_network

volumes:
    wordpress-files:
    mariadb-data:

networks:
    wordpress_network:
        driver: bridge
